name: Push to Space

on: push

jobs:

  push:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3
      - name: h
        run: |
          curl -fsSL https://get.deta.dev/space-cli.sh | sh
          echo '/home/runner/.detaspace/bin' >> $GITHUB_PATH
          echo "SPACE_ACCESS_TOKEN=${{ secrets.SPACE_ACCESS_TOKEN }}" >> $GITHUB_ENV
          ./.detaspace/bin/space new
      - uses: neobrains/space-deployment-github-action@v0.3

        with:

          access_token: ${{ secrets.SPACE_ACCESS_TOKEN }}

          project_id: ${{ secrets.SPACE_PROJECT_ID }}
