name: Push to Space

on: push

jobs:

  push:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - uses: neobrains/space-deployment-github-action@v0.3

        with:

          access-token: ${{ secrets.SPACE_ACCESS_TOKEN }}

          project-id: ${{ secrets.SPACE_PROJECT_ID }}
